### ISSUE TITLE
Use native Web APIs

### ISSUE THREAD

**Issue by bjesus** [daggett206/managed-component-snowplow#1]
Hey, thank you for creating this component!

For better support with Cloudflare Zaraz and the Managed Component standard, do you think you can get rid of the `uuid` and `sha1` package? Both should be easily replaced by native APIs such as https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest and https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by daggett206** [comment]
thanks @bjesus, replaced `uuid` and `sha1` with built-in crypto module's methods

**Comment by daggett206** [comment]
@bjesus could i ask you to check this issue?
https://github.com/daggett206/managed-component-snowplow/issues/3
