### ISSUE TITLE
How to get screen resolution, charset, colorDepth properties?

### ISSUE THREAD

**Issue by daggett206** [daggett206/managed-component-snowplow#3]
I didn't manage to find a way how to get values for these properties in webcm environment, but since his component is for Zaraz, there is should be a way to get them from `device` object, i just don't know where it is located. could you help me to replace these hardcoded values with values from `device` object? 

https://github.com/daggett206/managed-component-snowplow/blob/main/src/payload-builder.ts#L29

thanks!

**Comment by bjesus** [comment]
Hey @daggett206 - can you elaborate on the reasons you need access to these parameters? They are currently not supported in Managed Components.

**Comment by daggett206** [comment]
sure @bjesus , i need these parameters to construct the values for these 4 fields required for Snowplow request:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/14615740/220417988-92ac1745-3f48-402b-939f-7bab0939d250.png">

at the moment, there are hardcoded, but much better to construct these values based on `device` object

**Comment by bjesus** [comment]
The screen resolution (and viewport) is available https://github.com/managed-components/types/blob/main/index.d.ts#L81-L84 in Zaraz (WebCM doesn't support it yet). For now would it be okay to start with these, and we'll see about adding support for colordepth and charset later?
